bin: Improve compress pdf script

diff --git a/local/bin/compress-pdf b/local/bin/compress-pdf
--- a/local/bin/compress-pdf
+++ b/local/bin/compress-pdf
@@ -10,14 +10,20 @@ fi
 INPUT=${@: 1:$#-1}
 OUTPUT=${@: -1}
 
+for f in "${INPUT[@]}"; do
+    if [[ ! -f $f ]]; then
+        echo "File $f not found"
+        exit 2
+    fi
+done
+
 if [[ ${OUTPUT: -3}  != "pdf" ]]; then
     echo "output-file must be pdf, but got '$OUTPUT'."
-    exit 2
+    exit 3
 fi
 
 TMP=$(mktemp --suffix='.pdf' /tmp/compress.XXXXXXXXX)
 
-echo "convert $INPUT $TMP"
-convert $INPUT $TMP
-gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=$OUTPUT $TMP
-rm $TMP
+gs -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE \
+    -dQUIET -dBATCH -sOutputFile=$TMP $INPUT
+mv $TMP $OUTPUT
