bin: Use lock file for edp toggle

diff --git a/local/bin/eDP1-toggle b/local/bin/eDP1-toggle
--- a/local/bin/eDP1-toggle
+++ b/local/bin/eDP1-toggle
@@ -1,12 +1,34 @@
 #!/bin/bash
 
 IS_ENABLED=$(swaymsg -t get_outputs | jq '.[] | select(.name=="eDP-1").active')
+LOCK_FILE="$HOME/.edp1lock"
+
+for ((i = 0; i < 100; i++)); do
+  if [ -f "$LOCK_FILE" ]; then
+    break
+  fi
+  sleep 10ms
+done
+if [ -f "$LOCK_FILE" ]; then
+  echo "Could not lock .edp1lock"
+  exit 1
+fi
+
+touch $LOCK_FILE
 
 if [ "$IS_ENABLED" == "false" ]; then
   echo is false
 fi
 if [ "$IS_ENABLED" == "true" ]; then
-  swaymsg output eDP-1 disable
+  NUM_OUTPUTS=$(swaymsg -t get_outputs | jq '.[].name' | wc -l)
+  if [ "$NUM_OUTPUTS" -gt 1 ]; then
+    swaymsg output eDP-1 disable
+  else
+    echo "No other monitor connected"
+    exit 1
+  fi
 else
   swaymsg output eDP-1 enable
 fi
+
+rm "$LOCK_FILE"
