bin: Proper html parsing for heute-journal

diff --git a/local/bin/heute-journal b/local/bin/heute-journal
--- a/local/bin/heute-journal
+++ b/local/bin/heute-journal
@@ -2,9 +2,33 @@
 
 
 BASE_URL="https://www.zdf.de"
-LATEST=$(curl -s "$BASE_URL"/nachrichten/heute-journal | sed -n '/<h2.*>Ganze Sendungen<\/h2>/,$p' | rg -m 1 href)
-HREF=$(echo $LATEST | cut -d'"' -f 2)
-TITLE=$(echo $LATEST | cut -d'"' -f 4)
 
-echo "Playing $TITLE"
-ytplay "$BASE_URL$HREF"
+if ! [ -x $(command -v pup) ]; then
+  echo "Html command line parsing tool 'pup' not found"
+  exit 1
+fi
+
+PLAYER=""
+if [ -x $(command -v yt) ]; then
+  PLAYER="yt"
+elif [ -x $(command -v mpv) ]; then
+  PLAYER="mpv"
+else
+  echo "No player found"
+  exit 2
+fi
+
+d=$(date -I)
+while true; do 
+  d=$(date -I -d "$d - 1 day")
+  formated=$(date --date $d +%d.%m.%Y)
+  title="heute journal vom $formated"
+  HREF=$(curl -s "$BASE_URL"/nachrichten/heute-journal | pup 'a[title="'"$title"'"] attr{href}' | head -n 1)
+  URL=$BASE_URL$HREF
+  if curl --head --silent --fail $URL >/dev/null 2>&1; then
+    break
+  fi
+done
+
+echo "Playing $title"
+$PLAYER "$BASE_URL$HREF"
